### ISSUE TITLE
Choice of sparsity for degree centrality

### ISSUE THREAD

**Issue by wizofe** [yooha1003/uta-rest#1]
Hi, 

thanks for sharing your great workflow! How did you end up with sparsity 1 and threshold 0.5? I've seen that usually publications would aim for 0.20,0.25 threshold and sparsity 1 but usually not simultaneusouly. Do you have some experiments or publications to back this up?

Thanks!

**Comment by yooha1003** [comment]
Hi,
Thanks for checking my pipeline and giving feedback.
I set the threshold 0.5 due to my current dataset needing a more strict number of edges.
I think that the threshold could be selected according to the study's aims.
You can check some papers below using higher thresholds.
1. https://www.sciencedirect.com/science/article/pii/S1876201820301672
2. http://nemolaboratory.com/nemo/wp-content/uploads/2020/01/2019_Oliva-et-al_Int-J-Eat-Disord.pdf

I will consider adding a function for changing the threshold in the next version.
Please feel free to ask if you have any questions!
Cheers!

**Comment by yooha1003** [comment]
I close this issue.

**Comment by wizofe** [comment]
This is great, thank you for your answer and pointers. Based on the publications of my interest it seems though that a sparsity close to [0.2, 0.25] is more suitable!

**Comment by yooha1003** [comment]
Thanks for your reply, have a great day :)
